### ISSUE TITLE
SDK won't compile with UE4.15

### ISSUE THREAD

**Issue by KiaArmani** [PlayFab/UnrealBlueprintSDK#46]
After migrating to UE4.15 from 4.14.3 I get tons of these error when compiling

`PlayFab.generated.1.cpp(16692): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'`

Full log

```
> 1>------ Build started: Project: Speedsucht, Configuration: DebugGame_Editor x64 ------
> 1>  Performing full C++ include scan (building a new target)
> 1>  Creating makefile for SpeedsuchtEditor (no existing makefile)
> 1>  Performing 19 actions (4 in parallel)
> 1>  PCH.PlayFab.cpp
> 1>  PCH.Speedsucht.cpp
> 1>  Module.LoadingScreen.cpp
> 1>  LoadingScreen.generated.cpp
> 1>  [5/19] Resource PCLaunch.rc
> 1>  [6/19] Resource PCLaunch.rc
> 1>  [7/19] Resource PCLaunch.rc
> 1>  [8/19] Link UE4Editor-LoadingScreen-Win64-DebugGame.dll
> 1>  [9/19] Link UE4Editor-LoadingScreen-Win64-DebugGame.lib
> 1>     Creating library D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\LoadingScreen\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-LoadingScreen-Win64-DebugGame.lib and object D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\LoadingScreen\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-LoadingScreen-Win64-DebugGame.exp
> 1>     Creating library D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\LoadingScreen\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-LoadingScreen-Win64-DebugGame.suppressed.lib and object D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\LoadingScreen\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-LoadingScreen-Win64-DebugGame.suppressed.exp
> 1>  CompileME.cpp
> 1>  Speedsucht.cpp
> 1>  [12/19] Link UE4Editor-Speedsucht-Win64-DebugGame.dll
> 1>  [13/19] Link UE4Editor-Speedsucht-Win64-DebugGame.lib
> 1>     Creating library D:\gamedev\Speedsucht\Speedsucht_Game\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-Speedsucht-Win64-DebugGame.lib and object D:\gamedev\Speedsucht\Speedsucht_Game\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-Speedsucht-Win64-DebugGame.exp
> 1>     Creating library D:\gamedev\Speedsucht\Speedsucht_Game\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-Speedsucht-Win64-DebugGame.suppressed.lib and object D:\gamedev\Speedsucht\Speedsucht_Game\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-Speedsucht-Win64-DebugGame.suppressed.exp
> 1>  PlayFab.generated.2.cpp
> 1>  Module.PlayFab.2_of_2.cpp
> 1>  PlayFab.generated.1.cpp
> 1>  Module.PlayFab.1_of_2.cpp
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.2.cpp(7552): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15106): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15155): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15189): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15220): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15248): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15275): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15317): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15358): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15387): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15420): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15453): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15485): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15515): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15546): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15575): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15601): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15628): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15660): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15691): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15728): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15768): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15796): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(15981): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(16414): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Intermediate\Build\Win64\UE4Editor\Inc\PlayFab\PlayFab.generated.1.cpp(16692): error C2664: 'bool UEnum::SetEnums(TArray<TPair<FName,int64>,FDefaultAllocator> &,UEnum::ECppForm,bool)': cannot convert argument 1 from 'TArray<TPair<FName,uint8>,FDefaultAllocator>' to 'TArray<TPair<FName,int64>,FDefaultAllocator> &'
> 1>ERROR : UBT error : Failed to produce item: D:\gamedev\Speedsucht\Speedsucht_Game\Plugins\PlayFab\Binaries\Win64\UE4Editor-PlayFab-Win64-DebugGame.dll
> 1>  Total build time: 52,26 seconds (Local executor: 0,00 seconds)
> 1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.targets(41,5): error MSB3075: The command ""C:\Program Files (x86)\Epic Games\UE_4.15\Engine\Build\BatchFiles\Build.bat" SpeedsuchtEditor Win64 DebugGame "D:\gamedev\Speedsucht\Speedsucht_Game\Speedsucht.uproject" -waitmutex" exited with code 5. Please verify that you have sufficient rights to run this command.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by KiaArmani** [comment]
After deleting all generated folders (Binaries, Intermediate & Saved) it works now.
